package rocks.m2x.demo.service.mcp;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.core.io.Resource;
import rocks.m2x.demo.config.McpProperties;
import rocks.m2x.demo.mcp.model.TemplateMetadata;

import java.io.File;
import java.io.FileOutputStream;
import java.nio.file.Path;
import java.util.Base64;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for TemplateResourceService
 */
class TemplateResourceServiceTest {

    @TempDir
    Path tempDir;

    private TemplateResourceService service;
    private McpProperties properties;

    @BeforeEach
    void setUp() {
        properties = new McpProperties();
        properties.setTempStorageDir(tempDir.toString());
        properties.setMaxTemplateSize(10 * 1024 * 1024);
        properties.setTemplateTtl(java.time.Duration.ofHours(1));
        properties.setValidateTemplateContent(true);
        
        service = new TemplateResourceService(properties);
    }

    @Test
    void testCreateTemplateFromBase64() throws Exception {
        // Create a minimal valid DOCX file (ZIP signature)
        byte[] docxBytes = createMinimalDocx();
        String base64Content = Base64.getEncoder().encodeToString(docxBytes);

        TemplateMetadata metadata = service.createTemplateFromBase64(
                "test-template",
                base64Content,
                "Test template description"
        );

        assertNotNull(metadata);
        // Template ID is now always a UUID (server-generated), not user-provided name
        assertNotNull(metadata.getId());
        assertTrue(metadata.getId().matches("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"));
        // Name is stored separately from ID
        assertEquals("test-template", metadata.getName());
        assertEquals("Test template description", metadata.getDescription());
        assertNotNull(metadata.getUploaded());
    }

    @Test
    void testCreateTemplateWithAutoGeneratedId() throws Exception {
        byte[] docxBytes = createMinimalDocx();
        String base64Content = Base64.getEncoder().encodeToString(docxBytes);

        TemplateMetadata metadata = service.createTemplateFromBase64(
                null,
                base64Content,
                null
        );

        assertNotNull(metadata);
        assertNotNull(metadata.getId());
        assertTrue(metadata.getId().length() > 0);
    }

    @Test
    void testGetTemplateResource() throws Exception {
        byte[] docxBytes = createMinimalDocx();
        String base64Content = Base64.getEncoder().encodeToString(docxBytes);

        TemplateMetadata metadata = service.createTemplateFromBase64(
                "test-template",
                base64Content,
                "Test template"
        );

        // Use the server-generated UUID, not the template name
        Resource resource = service.getTemplateResource(metadata.getId());
        assertNotNull(resource);
        assertTrue(resource.exists());
    }

    @Test
    void testGetTemplateResourceNotFound() {
        // Non-existent template ID (not in allowlist) should throw SecurityException
        assertThrows(SecurityException.class, () -> {
            service.getTemplateResource("non-existent");
        });
    }

    @Test
    void testListTemplates() throws Exception {
        byte[] docxBytes = createMinimalDocx();
        String base64Content = Base64.getEncoder().encodeToString(docxBytes);

        TemplateMetadata metadata1 = service.createTemplateFromBase64("template1", base64Content, "Template 1");
        TemplateMetadata metadata2 = service.createTemplateFromBase64("template2", base64Content, "Template 2");

        Map<String, TemplateMetadata> templates = service.listTemplates();
        assertEquals(2, templates.size());
        // Templates are keyed by UUID, not by name
        assertTrue(templates.containsKey(metadata1.getId()));
        assertTrue(templates.containsKey(metadata2.getId()));
        assertEquals("template1", templates.get(metadata1.getId()).getName());
        assertEquals("template2", templates.get(metadata2.getId()).getName());
    }

    @Test
    void testDeleteTemplate() throws Exception {
        byte[] docxBytes = createMinimalDocx();
        String base64Content = Base64.getEncoder().encodeToString(docxBytes);

        TemplateMetadata metadata = service.createTemplateFromBase64("test-template", base64Content, "Test");
        String templateId = metadata.getId();
        
        assertTrue(service.listTemplates().containsKey(templateId));
        
        service.deleteTemplate(templateId);
        
        assertFalse(service.listTemplates().containsKey(templateId));
    }

    @Test
    void testTemplateSizeValidation() {
        // Create content larger than max size
        String largeBase64 = Base64.getEncoder().encodeToString(new byte[(int) (properties.getMaxTemplateSize() + 1)]);

        assertThrows(IllegalArgumentException.class, () -> {
            service.createTemplateFromBase64("large-template", largeBase64, "Large");
        });
    }

    @Test
    void testInvalidDocxContent() {
        // Invalid content (not a valid DOCX/ZIP file)
        String invalidBase64 = Base64.getEncoder().encodeToString("Not a DOCX file".getBytes());

        assertThrows(IllegalArgumentException.class, () -> {
            service.createTemplateFromBase64("invalid-template", invalidBase64, "Invalid");
        });
    }

    @Test
    void testPathTraversalProtection() throws Exception {
        byte[] docxBytes = createMinimalDocx();
        String base64Content = Base64.getEncoder().encodeToString(docxBytes);

        // Test path traversal attempts in template name
        assertThrows(SecurityException.class, () -> {
            service.createTemplateFromBase64("../etc/passwd", base64Content, "Attack");
        });

        assertThrows(SecurityException.class, () -> {
            service.createTemplateFromBase64("subdir/../../etc/passwd", base64Content, "Attack");
        });

        assertThrows(SecurityException.class, () -> {
            service.createTemplateFromBase64("/absolute/path", base64Content, "Attack");
        });

        assertThrows(SecurityException.class, () -> {
            service.createTemplateFromBase64("C:\\Windows\\System32", base64Content, "Attack");
        });
    }

    /**
     * Create a minimal valid DOCX file (just ZIP signature)
     */
    private byte[] createMinimalDocx() throws Exception {
        // Create a minimal ZIP file that represents a valid DOCX
        // DOCX files are ZIP archives, so we need at least the ZIP signature
        File tempFile = File.createTempFile("test", ".docx");
        try (FileOutputStream fos = new FileOutputStream(tempFile)) {
            // ZIP file signature: 50 4B 03 04
            fos.write(0x50);
            fos.write(0x4B);
            fos.write(0x03);
            fos.write(0x04);
            // Add minimal ZIP content
            fos.write(new byte[100]);
        }
        
        byte[] bytes = java.nio.file.Files.readAllBytes(tempFile.toPath());
        tempFile.delete();
        return bytes;
    }
}
